export const ABOUT: string = '/about'
export const FISH_RECIPES: string = '/fish-recipes'
export const HOME: string = '/'
export const MEAT_RECIPES: string = '/meat-recipes'
export const VEGETARIAN_RECIPES: string = '/vegetarian-recipes'
